### ISSUE TITLE
Иксрей Карабин

### ISSUE THREAD

**Issue by Coureere** [animusdev/Old-World-Blue#101]
Иксрей карабин из карго по спрайту имеет такой же размер, как и обычный лазерный карабин, ёмкость конденсатора у него в два раза больше, лучи бьют больнее. При этом имеет вкласс меньший, чем у лазерного карабина и цепляется на пояс, но не на спину.

**Comment by Coureere** [comment]
Какое подтверждение? Проверьте размер и слот айтема в коде.

**Comment by ghost** [comment]
На моей памяти всегда так было.
Не зря же ящик называется "Experimental weapons crate".
К тому же, цена и недоступность в начале раунда балансит его.
