### ISSUE TITLE
Фабрикатор багует.

### ISSUE THREAD

**Issue by Fox231** [animusdev/Old-World-Blue#135]
Фабрикатор роботистов иногда багует и в него невозможно засунуть ничего кроме железа. У самого такое было, Соляр мне педально прописывал ресурсы в фабрикатор.

**Comment by ghost** [comment]
Кушай константы-переменные метала в фабрикаторе, проси еще.

**Comment by LethalGhost** [comment]
Типы проверяются строго, подтипы игнорируются. Например подтип "полный стак металла", которые и приходят в карго. Беда.
