### ISSUE TITLE
Доступ атмосферных техников

### ISSUE THREAD

**Issue by ghost** [animusdev/Old-World-Blue#138]
У атмосферных техников отсутствует доступ для использования переходных шлюзов выхода в космос. 
Говоря проще - за атмосферника не выйти в космос, доступа не хватает.

**Comment by alfacom** [comment]
В космосе нет атмосферы. Значит и атмосферникам там делать нечего.

**Comment by Seldorne** [comment]
А кто будет прокладывать кольца радиаторов, если не атмосферники? Хотя всё равно не нужно.
