### ISSUE TITLE
Манипуляторы и автолат

### ISSUE THREAD

**Issue by ghost** [animusdev/Old-World-Blue#145]
Манипуляторы не уменьшают стоимость создания предмета.
matter = list(DEFAULT_WALL_MATERIAL = 30000,"glass" = 15000) - базовая стоимость картриджа для РЦД.
matter cartridge 30000 steel, 15000 glass  - стоимость картриджа с пико манипулятором.

**Comment by alfacom** [comment]
Стандартный:
![default](https://cloud.githubusercontent.com/assets/1672524/21011914/902c4a30-bd64-11e6-91a1-884d00258a49.PNG)

Нано:
![nano-manipulator](https://cloud.githubusercontent.com/assets/1672524/21011916/902c9558-bd64-11e6-9171-773766b9585f.PNG)

Пико:
![default](https://cloud.githubusercontent.com/assets/1672524/21011915/902c6664-bd64-11e6-826b-e3872d1c2549.PNG)

**Comment by ghost** [comment]
Баффы на кончиках пальцев.

**Comment by LethalGhost** [comment]
Пошикшено.
