### ISSUE TITLE
Рантаймы

### ISSUE THREAD

**Issue by ghost** [animusdev/Old-World-Blue#149]
runtime error: Cannot read null.species
proc name: get icon (/obj/item/organ/external/proc/get_icon)
source file: organ_icon.dm,105
runtime error: undefined variable /obj/item/weapon/spellbook/var/air_contents
proc name: Stat (/mob/living/carbon/human/Stat)
source file: human.dm,67

**Comment by LethalGhost** [comment]
Появляется при Спауне боргом.
Из-за того, что МОБ спаунится человеком, но тут же превращается в борга. При этом, в органы не успевают получить иконки и получается вот это вот.
Будет исправлено с новым кодом органов.

**Comment by LethalGhost** [comment]
Пофикшено в #161.
