### ISSUE TITLE
Улучшения стиля нового меню

### ISSUE THREAD

**Issue by LethalGhost** [animusdev/Old-World-Blue#155]
Иссуй для обсуждения введения новых идей, исправления багов и прочего.
Основные идеи нового меню:
компактность, все в одном окне, группировка схожих свойств, более чистый и однозначный код.
Вызов нового меню:
setup в командную строку.

Вкладку подписанную, как Silicon предпологается использовать для настройки флавора.

**Comment by fey** [comment]
Через че менюшки делаются? HTML+JS? Может фронтенд разрабботчика поискать?

**Comment by LethalGhost** [comment]
@fey, yep. Собственно, код мы и сами напишем. Главное - стиль. Можно хоть в паинте нарисовать, если есть видение этого.

**Comment by fey** [comment]
Ну вы напишите чо там нужно, какие интерфейсы, можно и потыкать лул. Жалко, что там интернет эксплорер, можно было бы фреймворк какой годный впилить
