### ISSUE TITLE
Украдите с грина библиотеку, ваша сосет 

### ISSUE THREAD

**Issue by fey** [animusdev/Old-World-Blue#156]
Украдите с грина библиотеку, ваша сосет

**Comment by silentenemy** [comment]
<3

**Comment by LethalGhost** [comment]
Технику или наполнение?

**Comment by fey** [comment]
Наполнение (книги) не надо. Технику,  кейс для книг, планировку, игральные карты, мешочек с кубиками. 
У них, кстати, библиотека на старте заполняется частично, такие дела.
