### ISSUE TITLE
Страдания бедных одноруких мимов.

### ISSUE THREAD

**Issue by DeVerezzer** [animusdev/Old-World-Blue#160]
Играю я, значит, с одноруким персонажем. При спавне парамедиком обнаруживается, что я появляюсь без аптечки и лодаута, который спавнится в оной. Дело все в том, что если у тебя нет руки, в которой это должно спавниться (у парамедика аптечка спавнится в левой) - то ты появляешься без этого предмета. Можно ли попросить перенести спавн аптечек (да и вообще, подобных предметов, которые появляются в руках), в сумку?

**Comment by LethalGhost** [comment]
1) Оно спаунится не именно в руку. 
Код пребирает все предметы на персонаже, выбирает первый контейнер из них и спаунит предметы в него. Ведь есть профессии без ящиков в руках, они получают все в сумки.
2) После включения [нового кода спауна профессий](https://github.com/animusdev/Old-World-Blue/compare/jobs?expand=1) сумка будет приоритетным контейнером. Ну а если её нет, то включится старый код с поиком
