### ISSUE TITLE
Библиотека и ордеры

### ISSUE THREAD

**Issue by ghost** [animusdev/Old-World-Blue#201]
http://prntscr.com/dzg63p
Суть в том, что книга заказывается через ордеры. Ордер это цифра, идущая от 1 и до последней книги. Проблема в том, что цифры не отображаются и книги трудно заказывать, приходится считать от начала до нужной книги.
Предлагаю просто добавить порядковые номера для книг.

**Comment by EkuDza** [comment]
циферки есть, просто нужно увеличить\подвинуть окошко немного

**Comment by ghost** [comment]
Окей, закрываю.
