### ISSUE TITLE
Цвета Comfy Chair

### ISSUE THREAD

**Issue by fey** [animusdev/Old-World-Blue#206]
Просьба добавить **БЕЛЫЙ Comfy Chair**

beige comfy chair (2 sheets) 
black comfy chair (2 sheets) 
brown comfy chair (2 sheets) 
lime comfy chair (2 sheets) 
teal comfy chair (2 sheets) 
red comfy chair (2 sheets) 
blue comfy chair (2 sheets) 
purple comfy chair (2 sheets) 
green comfy chair (2 sheets)

**Comment by vetwiz** [comment]
>beige comfy chair
Куда тебе еще белее? #FFFFFF ?

**Comment by fey** [comment]
#f0ffff
