### ISSUE TITLE
Невоможно собрать нож-бабочку из пластила

### ISSUE THREAD

**Issue by fey** [animusdev/Old-World-Blue#214]
plasteel knife + knif gripe

собираем, отвертка
не собираецо

Предмет находился в рюкзаке, пишет plasteel unfinished coarcel knife

Короче хуйня какая-то

**Comment by Klausbarka** [comment]
Руки у тебя из жопы. И рукоятка и лезви собраны из пластали.
http://www.picshare.ru/uploads/170202/RazG87t294.png
