### ISSUE TITLE
Добавить переработку вторсырья.

### ISSUE THREAD

**Issue by fey** [animusdev/Old-World-Blue#226]
Добавить автомат для сбора бутылок, грязных тарелок, мусора и тд.
Бутылки генерируют стекло.
Пакеты, тарелки - пластик. Переработка в ресурсы/вещи.

**Comment by LethalGhost** [comment]
Автолат?

**Comment by fey** [comment]
Нахуй ты закрываещь епт. Автолат так-то находится у Каптера. 
И к тому что можно было бы сделоть подобие биогенератора, только ты бабло получаешь за сдачу говна.
Алсо еще не обсудили до конца принимает ли автолат или нет https://forum.ss13.ru/index.php?showtopic=12868&st=1240#entry543191

**Comment by alfacom** [comment]
Автолат у карго И РнД. Заказать автолат у инжей? Сбором мусора занимается
уборщик/борг, скидывает это в мусорку. А коптеру лень по одной штуке
сортировать мусор и он все скидывает в мусоросброс. Так что вся проблема в
кооперации с карго.

**Comment by fey** [comment]
Ну запилите фичу, чтобы из мусорного пакета можно было автоматически рассортировать перерабатываемое сырье. В тот же автолат чтобы загружалось.
