### ISSUE TITLE
Баг с инженерным Воид суитом.

### ISSUE THREAD

**Issue by fey** [animusdev/Old-World-Blue#228]
Одеваем, вкладка VOIDSUIT, жмем по Eject Voidsuit Tank 

На землю падает баллон с именем sorting junction (/list1)

**Comment by fey** [comment]
Подобрать его нельзя.

**Comment by fey** [comment]
Если в suit storage вставить другой баллон, нажать Eject Voidsuit Tank, то будет
>There is no tank inserted.

**Comment by FinnTheTurtle** [comment]
> Если в suit storage вставить другой баллон, нажать Eject Voidsuit Tank, то будет

Но это же не в Suit Storage, это прямо в него надо.

**Comment by LethalGhost** [comment]
@fey, вангую, что Т-рей сканер затмил твой взор.

**Comment by LethalGhost** [comment]
Иссуй перекрывается этим: #231
