### ISSUE TITLE
Новобеевская менюшка

### ISSUE THREAD

**Issue by Coureere** [animusdev/Old-World-Blue#230]
Нужен чарактер сетап с новобея или доделанный наш. Уже давно пора бы на самом деле, этот двухчасовой скроллинг по меню лоадаута меня порядком поздаебал, и объединения некоторой одежды таким офигительным способом это дело не упрощают.

**Comment by LethalGhost** [comment]
Почти готово.
Сейчас можно достать её через команду setup.
