### ISSUE TITLE
Требует теста - киборги+пайп диспенсоры

### ISSUE THREAD

**Issue by fey** [animusdev/Old-World-Blue#232]
Если борг открутит пайп диспенсер, потом прикрутить, то устройство не будет работать. Трубы не будут выдаваться.
Решается отвинчиванием и отвинчиванием человеком.
Еще потесчу, попробую подтвердить баг.

**Comment by Klausbarka** [comment]
А что не протестишь сам?

**Comment by fey** [comment]
В одном из раундов бага была. Если киборгов увижу, попрошу потестить.

**Comment by LethalGhost** [comment]
В коде нет каких-то различий между действиями киборгов/людей в этом отношении.
Возможно, совпадение.
