### ISSUE TITLE
gas cooling system

### ISSUE THREAD

**Issue by fey** [animusdev/Old-World-Blue#234]
После сборки у устройства спавнится в рандомных (слева справа сверху снизу) труба-коннектор. Повлиять на это нельзя. Коннектор устройства может построиться возле стены к примеру, что приведет к его разборке.

**Comment by fey** [comment]
Труба спавнится с противоположной стороны от персонажа.
в центре устройство, мы с запада, смотрим на восток, собираем, труба спавнится с восточной стороны.
Сделоть, чтобы спавнилась с той стороны, где персонаж стоит

**Comment by Camper12345** [comment]
Надо при сборке машин фрейма смотреть в ту сторону, в которую должна торчать труба.
