### ISSUE TITLE
Буква Я при записи лога

### ISSUE THREAD

**Issue by fey** [animusdev/Old-World-Blue#243]
пкм  - Log...

При сохранении лога буква Я пидорасится в &#255;

**Comment by fey** [comment]
На инфинити (тг билд) с этим проблем нет.

**Comment by fey** [comment]
https://github.com/infinitystation/-tg-station/tree/master/code их гит, где искать фикс я не знаю

**Comment by LethalGhost** [comment]
Кажется, придется смириться с этим.
