### ISSUE TITLE
Аугментации

### ISSUE THREAD

**Issue by Coureere** [animusdev/Old-World-Blue#245]
1 - запилить это всё ксенорасам.
2 - запилить потерю не только левого, но и правого глаза (+ повязку на правый глаз).
3 - как-нибудь сбалансить (?) панцирь, который даёт халявную защиту.

**Comment by Klausbarka** [comment]
Прозреваю, что введение очередного слота в UI не такое уж простое изменение.

**Comment by alfacom** [comment]
Вверно. Вон сколько лет просили анальный слот ввести.

**Comment by LethalGhost** [comment]
Не не, ребята, он не про отдельный Слот.
Он про возможность переключения повязки для ношения на левом/правом глазу.

**Comment by LethalGhost** [comment]
Собственно, сделано.
