### ISSUE TITLE
Добавить короткое замыкание

### ISSUE THREAD

**Issue by fey** [animusdev/Old-World-Blue#253]
Открытая панелька любого обьекта, где есть проводка и некий заряд электричества (айрлок, апц, автолаты, смесы и так далее) плюс вода сверху = короткое замыкание, взрыв АПЦ, пожар и прочее.

**Comment by Coureere** [comment]
У нас даже нет отдельных показателей силы тока и напряжения, какие нахер замыкания? Все будут ходить и лить воду на приборы.

**Comment by fey** [comment]
ну сила тока в проводке есть. Запилить простенькую зависимость повреждений от количества заряда батареи в АПЦ. Обливание водой машинерию ведет к обычному удару током (как без перчаток) + поломка.
Мож даже больше сделать - при  перегреве (перегрузке) проводка или машинерия (комьютеры) могут загораться, тушить их нужно песком.
