### ISSUE TITLE
Alcoholic language

### ISSUE THREAD

**Issue by ghost** [animusdev/Old-World-Blue#258]
Round not ended, sorry for name (follow) slobbers, "Ви<b>д</b>и<b>м</b>о,<b> </b>Я скоро <b>у</b>мрУ... Так-чТО проЩ<b>а</b>Йте<b>.</b>.."

**Comment by LethalGhost** [comment]
????

**Comment by Camper12345** [comment]
Информативность.

**Comment by ghost** [comment]
http://prntscr.com/eh387a
Гит преобразовал теги.

**Comment by LethalGhost** [comment]
:)
