### ISSUE TITLE
Граб

### ISSUE THREAD

**Issue by Coureere** [animusdev/Old-World-Blue#268]
После броска кого-нибудь посредством граба твой персонаж хватает паралич на три-пять секунд, с которым ничего нельзя сделать.

**Comment by Klausbarka** [comment]
Это же фича. Занерфали, дабы не спамили этим.

**Comment by Coureere** [comment]
Это именно бажный стан. Я бы ещё понял кулдаун на граб.

**Comment by LethalGhost** [comment]
Он скорее не сбалансированный.

**Comment by Coureere** [comment]
Так сбалансируй. Это выглядит и играется как серьёзный баг, когда я за ниндзю, бросив сбшника стою и втыкаю 5 секунд без возможности управлять даже сраным костюмом.
