### ISSUE TITLE
Взрывы

### ISSUE THREAD

**Issue by Coureere** [animusdev/Old-World-Blue#271]
В этом иссуе я попробую вырезать первую половину раковой опухоли блю - трейторские бомбы и задания на террористические акты. Может, какой-нибудь Диманус или многоуважаемый Далек не согласятся с этим и скажут, мол, зато не аутизм)0)0, но нахуй слушать того, кто хвастает тем, что играет в победку 12 раундов подряд и того, кто в первые полчаса взрывает мед за генокрада с нулём генов? Каждый второй раунд станция находиться в полной пизде уже в первые пол часа. В конце раунда видно, что у трейтера было задание на подштанники СМО/Террористические акты, и на все кристаллы, он, конечно же, купил бомб.

Варианты решения:
-Выпилить задание на подрыв отсеков у трейторов или ОЧЕНЬ СИЛЬНО понизить шанс его возникновения, приблизительно один к ста.
-Нёрфать бомбы было бы нелогично, так что можно сильно бафнуть их цену в аплинке.
-Тиранить мамкиных подрывников с целькой на штаны СЕ.

Ещё хуже - лимиточники, особенно геносраки-лимиточники, но тут уже только воля педалей, которым, впрочем, вообще похуй на то, что происходит на сервере. Проблема лимиток грозится ещё долго быть нерешенной.

**Comment by Camper12345** [comment]
Это не решится, пока роль по правилам является лицензией на АБСОЛЮТНО, БЛЯТЬ ВСЁ. Может, даже на ИЦ ин ООЦ или на мультиаккерство.

**Comment by alfacom** [comment]
> Может, даже на ИЦ ин ООЦ или на мультиаккерство.

Чет хуйню спизданул.
По мне нужно не нерфать/бафать/тиранить, а давать стимул на рациональное использование.
Вот я сомневаюсь, что синдикат волнует исключительно то, добился ли результата их тритор или нет. Их также должно волновать эффективность действий. Поэтому предлагаю ввести рекомендованное кол-во кристаллов для задания. Надо спиздить чьи-то подштанники? Ставим в рекомендации цену е-мага. Ну или вместо цен сразу писать предметы. И самое главное, чтобы эта информация выдавалась в конце раунда, наряду с гринтекстом. Вот тут уже неэффективных можно и затиранить.

**Comment by Camper12345** [comment]
Некоторые за ролей, после выполнения заданий тупо грифонят. А педалям часто бывает похуй. Типо, роль лицензия на гриф.
