### ISSUE TITLE
крафт вещей из металла

### ISSUE THREAD

**Issue by fey** [animusdev/Old-World-Blue#274]
Короче, когда один листочек металла, крафтишь например решетку (metal rods), то решетка под ногами спавнится, а не в руках
то есть лист металла пропадает, предмет спавнится под ногами. Может с другими крафтами аналогично.
Неудобно очень.

**Comment by fey** [comment]
Сделать спавн под ногами только если у тебя рука занята будет

**Comment by LethalGhost** [comment]
Кстати, тоже думал об этом.
