### ISSUE TITLE
с тебя могут снять карточку и ремень, если ты в полном хардсуите

### ISSUE THREAD

**Issue by fey** [animusdev/Old-World-Blue#278]

**Comment by AtrocityKill** [comment]
Имеет смысл, кажется. Если ты можешь достать до своего ремня и вытащить из него что-то, то скорее всего, ремень прикреплен к хардсьюту, и, так как карточку прекрасно видно, даже если ты в полном хардсьюте, то, скорее всего, ее тоже можно снять, нет?
