### ISSUE TITLE
Охуевшее СБ и маг

### ISSUE THREAD

**Issue by Coureere** [animusdev/Old-World-Blue#295]
Предлагаю как на цивильных билдах анально огородить эквип мага так, чтоб его мог использовать только сам маг. Ёбаные сбшники используют орб, посох и прочую хуйню для победкоёбства. Да, соснул-нерфанул, но идея стоящая.

**Comment by alfacom** [comment]
Цивильные билды это те, где пушка перед выстрелом проверяет, состоишь ли ты
в СБ/Нюке или нет?

1 апреля 2017 г., 21:48 пользователь RandomColonist <
notifications@github.com> написал:

**Comment by Coureere** [comment]
Ну ты загнул, конечно.
Дело в том, что иногда бывает такая ситуация, что орб мага по той или иной причине попадает в руки сб - они моментально умеют им пользоваться и ищут им всяких недовольных и ассистух.
Посох изменения - это пиздец. Какой-нибудь даун помимо мага начинает бегать и морфить честный люд в киборгов/котов или другую ересь.
Лучше один даун с таким снаряжением и рестриктом на него, чем возможность использовать эту опаснейшую хуйню всему персоналу.
Гораздо опаснее какой-то там пушки, к слову.

**Comment by TermService** [comment]
Обычно маг сосёт, а посох переходит в грейтайд и это весело, иначе всё скатывается в эксту
