### ISSUE TITLE
Сortical Borer

### ISSUE THREAD

**Issue by Reishi42** [animusdev/Old-World-Blue#335]
На ночном раунде таки был борером. Проблема в том когда пытаешься вылезти из носителя (Release Host) ты выпадываешь мертвым, а также твой носитель становится трупом, а под конец феерично исчезает тело и носителя, и червя.

**Comment by HoltNox** [comment]
![image](https://user-images.githubusercontent.com/28760434/27017494-48c37f18-4f42-11e7-8016-d93178c5de94.png)

Привет. Это исправлено будет со следующим обновлением сервера.
