### ISSUE TITLE
выбор персонажа при входе в середине раунда

### ISSUE THREAD

**Issue by fey** [animusdev/Old-World-Blue#366]
Жмем Джоин Гейм. Выбираем персонажа, выбираем профессию.
Нахуя? Юзабилити бля, вместо того, чтобы нажимать 100 раз кнопки, сделать пару нажатий.
Удобно бля!

**Comment by RiyaMakary** [comment]
В чем проблема сейчас?
Сейчас вообще: join - профессия -  играешь. 
Что не так?

**Comment by fey** [comment]
В том, что у меня разные персонажи для разной ситуации. Как и у некоторых других игроков.

**Comment by LethalGhost** [comment]
Вроде, возможности нажать на имя персонажа и быстро выбрать другого, верно?

**Comment by fey** [comment]
Да, у тебя получается список проф, а сверху твои персонажи. МОжно добавить проверку, если персонаж мертв, то ты им не можешь зайти. Чтобы можно было заходить при респавне другими персонажами

**Comment by LethalGhost** [comment]
> МОжно добавить проверку, если персонаж мертв, то ты им не можешь

Такая уже есть.
