### ISSUE TITLE
пакеты с кровью

### ISSUE THREAD

**Issue by fey** [animusdev/Old-World-Blue#368]
при заполнении пактеа с кровью, он продолжает называться Empty BloodPack
Кроме того добавить вичу, чтобы можно было ручкой подписать группу крови и опционально имя донора.

**Comment by fey** [comment]
+добавить крафт пакетов для крови из автолата

**Comment by Voldirs** [comment]
> +добавить крафт пакетов для крови из автолата

Если не ошибаюсь, их можно делать из пластика и точно можно заказать в карго.
