### ISSUE TITLE
Реквест на 2 спрайта борга.

### ISSUE THREAD

**Issue by ghost** [animusdev/Old-World-Blue#60]
Суть:
Для шахтёрного борга - спрайт ВАЛЛ-И.
Для медицинского/исследовательского/инженерного - Дзенъятта.

Можно спрайты отдать другим под-типам боргов, чё уж там.

**Comment by ghost** [comment]
А сам спрайт где?

**Comment by ghost** [comment]
Ну блядь точно не у меня, итожиреквест на создание самого спрайта.
Я конечно, Валл-и могу попробовать сделать, но вряд ли будет нормально выглядеть.

**Comment by Coureere** [comment]
Валли уже на каком-то запендосском сервере видел, нужно поискать.

**Comment by alfacom** [comment]
Дзеньятта - инжборг? Он даже турели построить не может! Боевой тогда уж.

2016-10-29 14:34 GMT+03:00 RandomColonist notifications@github.com:
