### ISSUE TITLE
Красный шарф без иконки.

### ISSUE THREAD

**Issue by ghost** [animusdev/Old-World-Blue#68]
http://prntscr.com/d19c5g

**Comment by LethalGhost** [comment]
Последний раз у меня получилась клякса. Это не баг, спрайта просто нет.

**Comment by ghost** [comment]
В смысле нет, вообще для него подходящей иконки не было?

**Comment by LethalGhost** [comment]
Ну, выходит так. Только варианты на мобе.

**Comment by ghost** [comment]
Креч, посмотрю, поставлю иконку обычного красного шарфа, иль сам заспрайтю.
