### ISSUE TITLE
Система инвентаря

### ISSUE THREAD

**Issue by Madmannobrain** [animusdev/Old-World-Blue#7]
Господи, она же была десять из десяти, портировать необходимо определенно!

**Comment by ghost** [comment]
А нужно ли оно вообще?

**Comment by Madmannobrain** [comment]
Бля, ну ясное дело, что да. Поработать над в_классами предметов, к примеру, выпилить той же ионке возможность залезть в сумку - и вообще шикарно будет.

**Comment by ghost** [comment]
Как по мне - оно пока что сырое и хуйня.
Да, ультимейт дактейлс.

**Comment by amboyna** [comment]
Слоты - хуйня. А тут можно наложить бумаги больше, чем 10 штук в один рюкзак, вещь нужная.

**Comment by Madmannobrain** [comment]
В каком месте оно сырое, скажи мне?

**Comment by LethalGhost** [comment]
@amboyna,

> Слоты - хуйня. А тут можно наложить бумаги больше, чем 10 штук в один рюкзак, вещь нужная.

Справедливости для:
![1515](https://cloud.githubusercontent.com/assets/2458675/18777995/7fd244e2-818b-11e6-91a5-3274e432738a.png)
