### ISSUE TITLE
Автохисс

### ISSUE THREAD

**Issue by Coureere** [animusdev/Old-World-Blue#73]
Сделать автохисс отключаемым на кнопочку, но включенным по умолчанию. Хотя бы для пользователей войсчейнджеров.

**Comment by ghost** [comment]
Херня идея, ящеры которые НЕ ШИПЯТ :\

**Comment by amboyna** [comment]
Нет, нужная вещь. На полярисе была, только по умолчанию без акцента.

**Comment by LethalGhost** [comment]
Поддерживаю @Bill-Luxe 
Ящеры должны страдать, но не с войсчейнджером.
