### ISSUE TITLE
Магбутсы

### ISSUE THREAD

**Issue by Coureere** [animusdev/Old-World-Blue#79]
Дайте им кнопочку вкл/выкл, жутко неудобно, когда они постоянно активны.

**Comment by LethalGhost** [comment]
Это которые?

**Comment by Coureere** [comment]
> Это которые?

Абсолютно любые кроме тех, которые встроены в модульные риги.

**Comment by LethalGhost** [comment]
Есть множественные сообщения об обратном.
Нужно подтверждение.
