### ISSUE TITLE
Реворк охраны

### ISSUE THREAD

**Issue by Madmannobrain** [animusdev/Old-World-Blue#8]
Охрана на блубее была не очень в хорошем состоянии, так что мне стоило бы её привести в состояние получше. Унитаризация, решение вопроса со стрелковым, etc.

**Comment by Coureere** [comment]
Наконец-то он, блять, понял.

**Comment by alfacom** [comment]
> Наконец-то он, блять, понял.

Тихо! Спугнешь же!

**Comment by Coureere** [comment]
Спугнул.
