### ISSUE TITLE
Гиперспрей

### ISSUE THREAD

**Issue by Coureere** [animusdev/Old-World-Blue#83]
Не оставляет видимых логов, не имеет анимации, пробивает через скафандры. Такой генокрад в бутылочке. Убрать бы хотя бы пробиваемость.

**Comment by ghost** [comment]
> Не оставляет видимых логов.

Так надо. 

> не имеет анимации

Ват?

> пробивает через скафандры

 Глянем

**Comment by Coureere** [comment]
> Ват?

Когда бьёшь, то твой спрайт как-бы чуть подвигается на момент к оппоненту. Вот такой хуйни нет.

**Comment by FinnTheTurtle** [comment]
> Когда бьёшь, то твой спрайт как-бы чуть подвигается на момент к оппоненту. Вот такой хуйни нет.

Но ведь и не должна. А вот скафандры да, это недочёт.

**Comment by ghost** [comment]
There is no exposed flesh or thin material on their body to inject into.
