### ISSUE TITLE
Полярисофитчи

### ISSUE THREAD

**Issue by Fox231** [animusdev/Old-World-Blue#88]
ООС  Fox231: А еще на полярисе ALT+клик по ПДА можно было доставать ID карту. А еще на полярисе можно было тыкнуть по ящику ПДА, чтобы закрыть его. А еще на полярисе были пропуски максимум на 120 минут, а не 30 как здесь.
[Common] Ray Magnum asks, "Карго?"
ООС Zooopppaaa: че пасасал лазеропидор?
ООС RandomColonist: Это новобейские фичи.
ООС SolarEclipse84: На гитхаб
ООС SolarEclipse84: Пожалуйста.
*Поправил

**Comment by ghost** [comment]
Гляну.

**Comment by Coureere** [comment]
Ещё портануть бы родную фичу на переводы счетов на консоли ГП.

**Comment by LethalGhost** [comment]
> Euronem commented 18 hours ago
> Гляну.
> FinnTheTurtle was assigned by Euronem 4 hours ago

Лол.
