### ISSUE TITLE
Парамедикоштуки.

### ISSUE THREAD

**Issue by FinnTheTurtle** [animusdev/Old-World-Blue#89]
Пилю больше для себя, чтобы не забыть, что тут будет.
Немного доделать самостоятельный стиль парамедикам.

- [x] Свой гардероб.
- [x] Свой спрайт для сумок.
- [x] Чёрные нитриловые перчатки.
- [x] Небольшая смена карты для всего этого.
- [x] Изумрудные куртки и кепки с ТГ

**Comment by LethalGhost** [comment]
Уже есть спрайт для dufflebag.
