### ISSUE TITLE
A cup of spritebugz

### ISSUE THREAD

**Issue by ghost** [animusdev/Old-World-Blue#90]
Если от биогенератора открутить его стоковую бутылку, то она выпадет, но будет невидимая и неюзаемая
Монетка с ниткой пропадает, если её в инвентарь положить
[Player PM] Lunky-Dunk/(Lunky-Dunk)(?): и если достать из портсигара сигару, он откроеца, но если в него эту сигару положить обратно, то он улетучица

**Comment by LethalGhost** [comment]
![1515](https://cloud.githubusercontent.com/assets/2458675/20075738/44cefa94-a557-11e6-9757-92eef81b060b.png)

**Comment by LethalGhost** [comment]
Считаем закрытым до подтверждения.
