### ISSUE TITLE
Баги, сэр?

### ISSUE THREAD

**Issue by ghost** [animusdev/Old-World-Blue#92]
Мертвые маги могут колдовать.
При спавне рольки вылетает панель с админскими расами, в итоге мы имеем набегающих на станцию слаймов-нюкеров, ксеноморфов-магов и пауков-нюкеров.

**Comment by ghost** [comment]
Про двух ИИ во время малфа стоит напомнить.

**Comment by alfacom** [comment]
А это уже закос под фичу.

2016-11-08 21:35 GMT+03:00 Dallas notifications@github.com:

**Comment by ghost** [comment]
@alfacom Они спавнятся на одном и том же тайле.

**Comment by ghost** [comment]
fixed 9bcd835c60f75dc6430198ba6f3aec88f53a8c66
