### ISSUE TITLE
Хедсеты и своя речь.

### ISSUE THREAD

**Issue by ghost** [animusdev/Old-World-Blue#95]
![image](https://cloud.githubusercontent.com/assets/17518355/20116679/4b867cce-a60e-11e6-85ef-ed04b786a00b.png)
Происходит что-то вроде этого. Ты не слышишь свою речь, но ее слышат другие.

**Comment by LethalGhost** [comment]
Таки баг есть?
В целом, курсив отмечает то, что ты говорил в хедсет, а не просто так.

**Comment by alfacom** [comment]
Баг не обнаружен
![default](https://cloud.githubusercontent.com/assets/1672524/21012350/95969a1e-bd66-11e6-97f2-e7455f00447c.PNG)

**Comment by LethalGhost** [comment]
Закрываем до подтверждения.
